import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin } from 'react-icons/ai';
import { BsKeyboard } from 'react-icons/bs';
import Image from 'next/image';
import headshot from '../public/headshot.jpeg';
import proj1 from '../public/proj-1.png';
import proj3 from '../public/proj-3.png';
import proj4 from '../public/proj-4.png';
import { useState } from "react";

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Brandon Hernandez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-mono'>Brandon Hernandez</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} 
                className='cursor-pointer text-xl' 
                />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Brandon Hernandez</h2>
            <h3 className='text-3xl py-2 md:text-3xl'>Full-Stack Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>Personal Trainer turned full-stack software engineer.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <a href="https://www.linkedin.com/in/brandon-a-hernandez/" target="_blank" rel="noopener noreferrer">< AiFillLinkedin /></a>
          </div>
          <div className='relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={headshot} alt="headshot" layout='fill' objectFit='cover' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>More about me</h3>
            <p className='text-md py-2 leading-8 text-gray-80'>
              <span className="text-teal-500">Queens, NY</span> native with love for all things <span className="text-teal-500">tech</span>, <span className="text-teal-500">fitness</span>, and everywhere in between. 
              Thanks for stopping by! Feel free to reach me through my 
              <span className="text-teal-500"><a href="https://www.linkedin.com/in/brandon-a-hernandez/" target="_blank" rel="noopener noreferrer"> Linkedin</a></span>, 
              always open to connecting and learning from others!
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <BsKeyboard size={100} color={"grey"} />
              <h3>Skills</h3>
              <p>Javascript</p>
              <p>Python</p>
              <p>HTML</p>
              <p>CSS</p>
              <p>Node</p>
              <p>Express</p>
              <p>React</p>
              <p>Django</p>
              <p>Tailwind CSS</p>
              <p>PostgreSQL</p>
              <p>MongoDB</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <BsKeyboard size={100} color={"grey"} />
              <h3>Skills</h3>
              <p>Javascript</p>
              <p>Python</p>
              <p>HTML</p>
              <p>CSS</p>
              <p>Node</p>
              <p>Express</p>
              <p>React</p>
              <p>Django</p>
              <p>Tailwind CSS</p>
              <p>PostgreSQL</p>
              <p>MongoDB</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <BsKeyboard size={100} color={"grey"} />
              <h3>Skills</h3>
              <p>Javascript</p>
              <p>Python</p>
              <p>HTML</p>
              <p>CSS</p>
              <p>Node</p>
              <p>Express</p>
              <p>React</p>
              <p>Django</p>
              <p>Tailwind CSS</p>
              <p>PostgreSQL</p>
              <p>MongoDB</p>
            </div>
          </div>


          {/* <div className='flex justify-content'>
            <div className='flex'>
              <Image  src={proj4} width={100} height={100} />
              <Image  src={proj3} />
              <Image  src={proj1} />

            </div>
          </div> */}
        </section>
        <section>
          <div>
          <h3 className='text-3xl py-1'>Projects</h3>
            <p className='text-md py-2 leading-8 text-gray-80'>
              <span className="text-teal-500">Queens, NY</span> native with love for all things <span className="text-teal-500">tech</span>, <span className="text-teal-500">fitness</span>, and everywhere in between. 
              Thanks for stopping by! Feel free to reach me through my 
              <span className="text-teal-500"><a href="https://www.linkedin.com/in/brandon-a-hernandez/" target="_blank" rel="noopener noreferrer"> Linkedin</a></span>, 
              always open to connecting and learning from others!
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={proj1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={proj3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={proj4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
